import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js";
const canvas=document.getElementById("scene"),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x05080d);scene.fog=new THREE.Fog(0x05080d,18,90);const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,150);camera.position.set(0,1.62,1.2);const clock=new THREE.Clock();const train=new THREE.Group();scene.add(train);
const mats={floor:new THREE.MeshStandardMaterial({color:0x17222d,metalness:.65,roughness:.32}),wall:new THREE.MeshStandardMaterial({color:0x253341,metalness:.55,roughness:.35}),seat:new THREE.MeshStandardMaterial({color:0x163a5d,metalness:.25,roughness:.5}),metal:new THREE.MeshStandardMaterial({color:0x9aa9b7,metalness:.85,roughness:.2}),glow:new THREE.MeshStandardMaterial({color:0x64cfff,emissive:0x1688bb,emissiveIntensity:2.2}),dark:new THREE.MeshStandardMaterial({color:0x071018,metalness:.6,roughness:.25}),glass:new THREE.MeshPhysicalMaterial({color:0x183f5d,transparent:true,opacity:.38,metalness:.1,roughness:.08})};
function box(w,h,d,mat,x,y,z,parent=train){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.position.set(x,y,z);parent.add(m);return m}function seat(x,z,flip=false){const g=new THREE.Group();g.position.set(x,0,z);train.add(g);box(1.15,.16,.48,mats.seat,0,.63,0,g);box(1.15,.72,.13,mats.seat,0,1.02,flip?-.22:.22,g);box(.10,.56,.55,mats.metal,-.48,.56,0,g);box(.10,.56,.55,mats.metal,.48,.56,0,g)}
box(6,.12,42,mats.floor,0,0,0);box(.12,2.8,42,mats.wall,-3.05,1.4,0);box(.12,2.8,42,mats.wall,3.05,1.4,0);box(6,.12,42,mats.dark,0,3.05,0);for(let z=-19;z<=19;z+=3.2){box(.16,.05,2.3,mats.glow,-1.35,2.92,z);box(.16,.05,2.3,mats.glow,1.35,2.92,z)}for(let z=-18.5;z<=18.5;z+=4.2){box(.04,1.25,3.15,mats.glass,-3.01,1.85,z);box(.04,1.25,3.15,mats.glass,3.01,1.85,z)}for(let z=-18;z<=18;z+=2.8){seat(-2.35,z,false);seat(2.35,z,true)}for(let z=-19;z<=19;z+=3.2){box(.06,2.35,.06,mats.metal,-1.15,1.25,z);box(.06,2.35,.06,mats.metal,1.15,1.25,z);box(5.2,.05,.05,mats.metal,0,2.38,z)}
function endDoor(z){box(2.2,2.2,.16,mats.dark,0,1.45,z);box(1.05,2,.18,mats.glass,-.58,1.45,z-.11);box(1.05,2,.18,mats.glass,.58,1.45,z-.11);box(.08,2.1,.22,mats.glow,-1.13,1.45,z-.2);box(.08,2.1,.22,mats.glow,1.13,1.45,z-.2)}endDoor(-20.65);endDoor(20.65);
const tablet=new THREE.Group();tablet.position.set(1.45,1.25,1.0);tablet.rotation.y=-.22;train.add(tablet);box(1.55,1.1,.12,mats.dark,0,0,0,tablet);box(1.35,.88,.03,mats.glow,0,0,.07,tablet);box(1.43,.08,.12,mats.metal,0,-.62,0,tablet);
const outside=new THREE.Group();scene.add(outside);const cityMats=[0x10243a,0x17334b,0x0d1a29,0x20455f];for(let i=0;i<75;i++){const h=2+Math.random()*12,w=1.2+Math.random()*3,d=1.5+Math.random()*3;b=box(w,h,d,new THREE.MeshStandardMaterial({color:cityMats[i%4],metalness:.25,roughness:.65}),0,0,0,outside);b.position.set((Math.random()<.5?-1:1)*(7+Math.random()*18),h/2,Math.random()*180-90)}for(let z=-90;z<90;z+=5){box(.12,.12,1.4,mats.glow,-5.3,2.4,z,outside);box(.12,.12,1.4,mats.glow,5.3,2.4,z,outside)}scene.add(new THREE.HemisphereLight(0x9acbff,0x05070a,1.7));const key=new THREE.DirectionalLight(0xffffff,1.3);key.position.set(0,5,5);scene.add(key);
let running=false,traveling=false,selectedStation="",lookYaw=0,lookPitch=0,zoom=72,dragging=false,lastX=0,lastY=0,t=0,travelStart=null;const tabletUI=document.getElementById("tabletUI"),stationHud=document.getElementById("stationHud"),arrival=document.getElementById("arrival"),arrivalTitle=document.getElementById("arrivalTitle"),stationPanel=document.getElementById("stationPanel"),stationTitle=document.getElementById("stationTitle"),stationText=document.getElementById("stationText");
function updateCamera(){camera.fov=zoom;camera.updateProjectionMatrix();camera.lookAt(new THREE.Vector3(Math.sin(lookYaw)*3,1.65+lookPitch,-Math.cos(lookYaw)*3))}function showTablet(){tabletUI.classList.remove("hidden")}function hideTablet(){tabletUI.classList.add("hidden")}
canvas.addEventListener("pointerdown",e=>{dragging=true;lastX=e.clientX;lastY=e.clientY});window.addEventListener("pointerup",()=>dragging=false);window.addEventListener("pointermove",e=>{if(!dragging||!running||traveling)return;lookYaw-=(e.clientX-lastX)*.004;lookPitch-=(e.clientY-lastY)*.0025;lookPitch=Math.max(-.55,Math.min(.45,lookPitch));lastX=e.clientX;lastY=e.clientY;updateCamera()});window.addEventListener("wheel",e=>{if(!running)return;zoom=Math.max(42,Math.min(92,zoom+(e.deltaY>0?3:-3)));updateCamera()});
document.querySelectorAll("#tabletUI button").forEach(btn=>btn.addEventListener("click",()=>{if(traveling)return;selectedStation=btn.dataset.station;document.getElementById("tabletStatus").textContent="ROUTE LOCKED: "+selectedStation;stationHud.textContent="ROUTE: "+selectedStation;traveling=true;hideTablet();arrivalTitle.textContent=selectedStation;arrival.classList.remove("hidden");setTimeout(()=>arrival.classList.add("hidden"),1800)}));
document.getElementById("backTrain").addEventListener("click",()=>{stationPanel.classList.add("hidden");traveling=false;stationHud.textContent="IN TRANSIT";showTablet()});document.getElementById("startBtn").addEventListener("click",()=>{document.getElementById("startOverlay").style.display="none";running=true;showTablet();updateCamera()});
function arrive(){traveling=false;stationHud.textContent="ARRIVED: "+selectedStation;stationTitle.textContent=selectedStation+" STATION";stationText.textContent=`Welcome to the ${selectedStation} station. This is the placeholder area for your portfolio content. Later we can replace this station with your models, videos, project details, images and interactive experiences.`;stationPanel.classList.remove("hidden")}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05);t+=dt;train.position.y=Math.sin(t*16)*.006;if(running&&traveling){outside.position.z=(outside.position.z+dt*18)%12;if(!travelStart)travelStart=t;const elapsed=t-travelStart;if(elapsed>4.8){travelStart=null;arrive()}}renderer.render(scene,camera)}animate();window.addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,2))});document.getElementById("loading").style.display="none";
